import type { Gender, CategorySlug, ProductDTO, VariantDTO, ReviewDTO } from "./types";

const IMG = "/images/products";
const G = (...slugs: string[]) => slugs.map((s) => `${IMG}/${s}.webp`);

const SIZES = ["5", "6", "7", "8", "9", "10", "11"];

export interface MockCollection {
  name: string;
  slug: string;
  tagline: string;
  story: string;
  image: string;
  count: number;
  sortOrder: number;
}

export const MOCK_COLLECTIONS: MockCollection[] = [
  {
    slug: "aqua",
    name: "Aqua",
    tagline: "Water Edition — Flow further. Go deeper.",
    story:
      "The first drop of the Elements Edition. AQUA takes its cue from moving water: wave-moulded sidewalls, a channelled outsole that clears water on contact, and a blue that shifts with the light.",
    image: `${IMG}/aqua-water-edition-sports-shoe-2.webp`,
    count: 1,
    sortOrder: 1,
  },
  {
    slug: "flare",
    name: "Flare",
    tagline: "Fire Edition — Bold energy. Powerful steps.",
    story:
      "Black knit wrapped in molten heat lines. FLARE is the loudest thing we make, and the most comfortable — a dual-density foam core keeps the noise on the outside.",
    image: `${IMG}/flare-fire-edition-sports-shoe-1.webp`,
    count: 1,
    sortOrder: 2,
  },
  {
    slug: "aero",
    name: "Aero",
    tagline: "Air Edition — Lighter steps. Move freely.",
    story:
      "Our lightest silhouette. Open-cell mesh, a foam midsole tuned for daily miles and a gum outsole that grips without the weight.",
    image: `${IMG}/aero-air-edition-sneaker-3.webp`,
    count: 1,
    sortOrder: 3,
  },
  {
    slug: "cinder",
    name: "Cinder",
    tagline: "Ash Edition — Stronger through it all.",
    story:
      "Built from what remains. CINDER is the all-terrain member of the family — an ash-washed upper over a lug pattern that handles monsoon tarmac as happily as dry trail.",
    image: `${IMG}/cinder-ash-edition-sports-shoe-3.webp`,
    count: 1,
    sortOrder: 4,
  },
  {
    slug: "denim",
    name: "Denim",
    tagline: "The Denim Edit — Worn in, never worn out.",
    story:
      "Washed denim on our everyday lasts, finished with gold-tone hardware. Loafers and low-tops in eight washes, cut for Indian streets and Indian weather.",
    image: `${IMG}/navy-denim-slip-on-loafer-1.webp`,
    count: 11,
    sortOrder: 5,
  },
];

export const MOCK_CATEGORIES = [
  { name: "Sports Shoes", slug: "sports" as CategorySlug, description: "Running, training and all-terrain performance shoes." },
  { name: "Sneakers", slug: "sneakers" as CategorySlug, description: "Everyday low-tops in canvas, denim and knit." },
  { name: "Loafers", slug: "loafers" as CategorySlug, description: "Slip-on loafers and drivers for smart-casual days." },
];

export const MOCK_REVIEWS_BY_SLUG: Record<string, ReviewDTO[]> = {
  "aqua-water-edition-sports-shoe": [
    { id: "rev-1", name: "Rohit Sharma", rating: 5, title: "Grip is unreal in the rain", body: "Bought these for the monsoon commute in Mumbai. Zero slips on wet platform tiles and they dried fast. Sizing is true to UK 9.", verified: true, createdAt: "2026-03-15T08:00:00Z" },
    { id: "rev-2", name: "Ananya Iyer", rating: 4, title: "Very light", body: "Comfortable from the first wear, no break-in needed. Only wish it came in more colours.", verified: true, createdAt: "2026-03-20T10:30:00Z" },
    { id: "rev-3", name: "Karan Mehta", rating: 5, title: "Box and packaging feel premium", body: "Presentation is top-notch. Wore them for a 12k step day and my feet were fine.", verified: true, createdAt: "2026-03-22T14:15:00Z" },
  ],
  "flare-fire-edition-sports-shoe": [
    { id: "rev-4", name: "Vikram Singh", rating: 5, title: "Head-turner", body: "Everyone at the gym asks about these. The red actually glows in photos. True to size.", verified: true, createdAt: "2026-03-10T11:00:00Z" },
    { id: "rev-5", name: "Sneha Rao", rating: 5, title: "Comfort + drama", body: "Was worried they'd be stiff because of the design but the midsole is soft. Love them.", verified: true, createdAt: "2026-03-18T16:20:00Z" },
    { id: "rev-6", name: "Aditya Kulkarni", rating: 4, title: "Great trainer", body: "Slightly narrow if you have wide feet — go half size up. Otherwise perfect.", verified: true, createdAt: "2026-03-25T09:40:00Z" },
  ],
  "aero-air-edition-sneaker": [
    { id: "rev-7", name: "Priya Nair", rating: 5, title: "Feels like nothing on foot", body: "Lightest shoes I own. The ivory does pick up dust but wipes clean with a damp cloth.", verified: true, createdAt: "2026-03-12T13:00:00Z" },
    { id: "rev-8", name: "Arjun Deshpande", rating: 4, title: "Excellent daily beater", body: "Three months in, foam has held up well. Gold detailing hasn't flaked.", verified: true, createdAt: "2026-03-28T18:10:00Z" },
  ],
  "cinder-ash-edition-sports-shoe": [
    { id: "rev-9", name: "Manish Verma", rating: 5, title: "Trail-ready", body: "Took these to Lonavala — grip on loose rock is genuinely good. Ankle support is solid.", verified: true, createdAt: "2026-03-05T07:30:00Z" },
    { id: "rev-10", name: "Divya Menon", rating: 4, title: "Runs slightly chunky", body: "Big silhouette, so size accordingly. Very cushioned for long walking days.", verified: true, createdAt: "2026-03-14T15:45:00Z" },
    { id: "rev-11", name: "Sameer Joshi", rating: 4, title: "Tough build", body: "Outsole shows barely any wear after a month. Ash wash looks better in person.", verified: true, createdAt: "2026-03-29T12:00:00Z" },
  ],
  "navy-denim-slip-on-loafer": [
    { id: "rev-12", name: "Rahul Bhatia", rating: 5, title: "Office to dinner", body: "Wears well with chinos and also with jeans. The gold bit detail is subtle and classy.", verified: true, createdAt: "2026-03-11T09:15:00Z" },
    { id: "rev-13", name: "Neha Agarwal", rating: 4, title: "Bought for my husband", body: "He lives in them now. Break-in took about a day.", verified: true, createdAt: "2026-03-26T17:30:00Z" },
  ],
  "black-denim-slip-on-loafer": [
    { id: "rev-14", name: "Imran Qureshi", rating: 5, title: "Versatile", body: "Goes with literally everything in my wardrobe. Comfortable straight out of the box.", verified: true, createdAt: "2026-03-17T14:00:00Z" },
  ],
  "white-denim-slip-on-loafer": [
    { id: "rev-15", name: "Tanya Bose", rating: 5, title: "Summer staple", body: "Perfect with linen. Sizing true to size, cushioning is better than expected.", verified: true, createdAt: "2026-03-21T10:00:00Z" },
  ],
  "black-denim-low-top-sneaker": [
    { id: "rev-16", name: "Aditi Shetty", rating: 5, title: "Best everyday sneaker", body: "Gold eyelets make it look far more expensive than it is. Comfortable for full days.", verified: true, createdAt: "2026-03-19T13:20:00Z" },
    { id: "rev-17", name: "Gaurav Malhotra", rating: 4, title: "Solid value", body: "Stitching is clean, sole is grippy. Slightly narrow.", verified: true, createdAt: "2026-03-24T16:50:00Z" },
  ],
};

function makeVariants(productSlug: string, colorName: string): VariantDTO[] {
  return SIZES.map((size) => ({
    id: `var-${productSlug}-${size}`,
    color: colorName,
    size,
    stock: size === "5" || size === "11" ? 3 : 15,
    sku: `AIR-${productSlug.slice(0, 6).toUpperCase()}-${size}`,
  }));
}

export const MOCK_PRODUCTS: ProductDTO[] = [
  {
    id: "prod-aqua-1",
    name: "Aqua Water Edition Sports Shoe",
    slug: "aqua-water-edition-sports-shoe",
    gender: "UNISEX",
    categorySlug: "sports",
    category: { name: "Sports Shoes", slug: "sports" },
    collectionSlug: "aqua",
    collection: { name: "Aqua", slug: "aqua", tagline: "Water Edition — Flow further. Go deeper." },
    colorName: "Aqua Blue",
    colors: [
      { name: "Aqua Blue", hex: "#2f6fd0" },
      { name: "White", hex: "#f5f5f4" },
    ],
    price: 3999,
    mrp: 6499,
    description:
      "Flow further. Go deeper. The AQUA Water Edition pairs a sculpted wave-moulded midsole with a water-channel outsole built for grip in wet conditions — monsoon commutes, pool decks and everything in between.",
    material: "Breathable engineered mesh upper, moulded TPU wave cage, memory-foam collar, phylon midsole, wet-grip rubber outsole",
    features: [
      "Multi-direction grip pattern — stability on every surface",
      "Water-channel outsole design for enhanced wet traction",
      "Lightweight cushioning with a 12 mm heel-to-toe drop",
      "Eco-friendly recycled mesh upper",
      "Reinforced heel pull tab for easy on/off",
    ],
    images: G(
      "aqua-water-edition-sports-shoe-1",
      "aqua-water-edition-sports-shoe-2",
      "aqua-water-edition-sports-shoe-4-poster",
      "aqua-water-edition-sports-shoe-3-poster"
    ),
    badge: "New",
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 4.7,
    reviewCount: 3,
    createdAt: "2026-03-01T00:00:00Z",
    variants: makeVariants("aqua-water-edition-sports-shoe", "Aqua Blue"),
  },
  {
    id: "prod-flare-1",
    name: "Flare Fire Edition Sports Shoe",
    slug: "flare-fire-edition-sports-shoe",
    gender: "UNISEX",
    categorySlug: "sports",
    category: { name: "Sports Shoes", slug: "sports" },
    collectionSlug: "flare",
    collection: { name: "Flare", slug: "flare", tagline: "Fire Edition — Bold energy. Powerful steps." },
    colorName: "Black / Red",
    colors: [
      { name: "Black / Red", hex: "#c2352b" },
      { name: "Black", hex: "#111111" },
    ],
    price: 4499,
    mrp: 6999,
    description:
      "Bold energy, powerful steps. FLARE wraps a black knit chassis in molten-red heat lines with gold AIROVA branding — an aggressive trainer built for people who like to be seen.",
    material: "Knit mesh upper with TPU heat-weld overlays, gold-tone metal eyelet stays, dual-density EVA midsole, abrasion rubber outsole",
    features: [
      "Molten heat-line TPU cage for lateral support",
      "Gold-tone AIROVA hardware and tongue badge",
      "Energy-return dual-density foam midsole",
      "Anti-slip herringbone traction pods",
      "Padded Achilles collar",
    ],
    images: G(
      "flare-fire-edition-sports-shoe-1",
      "flare-fire-edition-sports-shoe-4",
      "flare-fire-edition-sports-shoe-2-poster",
      "flare-fire-edition-sports-shoe-3-poster"
    ),
    badge: "Best Seller",
    featured: true,
    bestSeller: true,
    newArrival: false,
    active: true,
    rating: 4.8,
    reviewCount: 3,
    createdAt: "2026-03-02T00:00:00Z",
    variants: makeVariants("flare-fire-edition-sports-shoe", "Black / Red"),
  },
  {
    id: "prod-aero-1",
    name: "Aero Air Edition Sneaker",
    slug: "aero-air-edition-sneaker",
    gender: "UNISEX",
    categorySlug: "sports",
    category: { name: "Sports Shoes", slug: "sports" },
    collectionSlug: "aero",
    collection: { name: "Aero", slug: "aero", tagline: "Air Edition — Lighter steps. Move freely." },
    colorName: "Ivory / Gold",
    colors: [
      { name: "Ivory / Gold", hex: "#efe6d4" },
      { name: "Gum Gold", hex: "#c89a52" },
    ],
    price: 4299,
    mrp: 6799,
    description:
      "Lighter steps. Move freely. AERO is our lightest silhouette yet — ivory mesh, brushed gold detailing and a gum outsole that softens every landing.",
    material: "Open-cell breathable mesh, synthetic leather overlays, gold foil branding, AERO-FOAM midsole, natural gum rubber outsole",
    features: [
      "Ultra-lightweight build — under 280 g per shoe",
      "Breathable comfort mesh keeps feet cool all day",
      "All-day arch support footbed",
      "Flex grooves for natural movement",
      "Sustainable, recycled-content materials",
    ],
    images: G(
      "aero-air-edition-sneaker-3",
      "aero-air-edition-sneaker-1",
      "aero-air-edition-sneaker-2-poster",
      "aero-air-edition-sneaker-4-poster",
      "aero-air-edition-sneaker-5-poster"
    ),
    badge: "New",
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 4.6,
    reviewCount: 2,
    createdAt: "2026-03-03T00:00:00Z",
    variants: makeVariants("aero-air-edition-sneaker", "Ivory / Gold"),
  },
  {
    id: "prod-cinder-1",
    name: "Cinder Ash Edition Sports Shoe",
    slug: "cinder-ash-edition-sports-shoe",
    gender: "UNISEX",
    categorySlug: "sports",
    category: { name: "Sports Shoes", slug: "sports" },
    collectionSlug: "cinder",
    collection: { name: "Cinder", slug: "cinder", tagline: "Ash Edition — Stronger through it all." },
    colorName: "Charcoal / Ash",
    colors: [
      { name: "Charcoal", hex: "#2b2b2b" },
      { name: "Ash Gold", hex: "#b9a489" },
    ],
    price: 4199,
    mrp: 6699,
    description:
      "Stronger through it all. CINDER is built from what remains — an ash-washed upper over a rugged all-terrain outsole that swallows tarmac, trail and everything in between.",
    material: "Ash-washed textile upper, welded stone-print overlays, shock-absorption EVA carrier, high-grip carbon rubber outsole",
    features: [
      "All-terrain lug pattern for road and trail",
      "Durable rubber outsole built for longer journeys",
      "Shock-absorption technology at the heel",
      "Long-lasting performance build",
      "Inspired by raw elements",
    ],
    images: G(
      "cinder-ash-edition-sports-shoe-3",
      "cinder-ash-edition-sports-shoe-2-poster",
      "cinder-ash-edition-sports-shoe-1-poster",
      "cinder-ash-edition-sports-shoe-4-poster"
    ),
    badge: "Best Seller",
    featured: true,
    bestSeller: true,
    newArrival: false,
    active: true,
    rating: 4.5,
    reviewCount: 3,
    createdAt: "2026-03-04T00:00:00Z",
    variants: makeVariants("cinder-ash-edition-sports-shoe", "Charcoal / Ash"),
  },
  {
    id: "prod-denim-1",
    name: "Navy Denim Slip-On Loafer",
    slug: "navy-denim-slip-on-loafer",
    gender: "MEN",
    categorySlug: "loafers",
    category: { name: "Loafers", slug: "loafers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Navy",
    colors: [{ name: "Navy", hex: "#1f2f52" }],
    price: 2299,
    mrp: 3699,
    description:
      "A penny-loafer cut in washed indigo denim with a hand-finished gold AIROVA pin. Dressy enough for the office, relaxed enough for Sunday brunch.",
    material: "Washed denim upper, tan cushioned leatherette lining, memory footbed, stitched whipstitch detail, EVA wedge with rubber grip pods",
    features: [
      "Gold-tone AIROVA metal bit detail",
      "Slip-on construction with elastic gussets",
      "Cushioned, breathable insole",
      "Stitched whipstitch detail on the apron",
      "Non-marking durable outsole",
    ],
    images: G("navy-denim-slip-on-loafer-1"),
    badge: null,
    featured: false,
    bestSeller: false,
    newArrival: false,
    active: true,
    rating: 4.4,
    reviewCount: 2,
    createdAt: "2026-03-05T00:00:00Z",
    variants: makeVariants("navy-denim-slip-on-loafer", "Navy"),
  },
  {
    id: "prod-denim-2",
    name: "Black Denim Slip-On Loafer",
    slug: "black-denim-slip-on-loafer",
    gender: "MEN",
    categorySlug: "loafers",
    category: { name: "Loafers", slug: "loafers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Black",
    colors: [{ name: "Black", hex: "#111111" }],
    price: 2299,
    mrp: 3699,
    description:
      "Deep-black washed denim over a crisp ivory sole — the quiet flex. Gold hardware keeps it unmistakably AIROVA.",
    material: "Washed black denim upper, tan cushioned lining, memory footbed, EVA wedge with rubber grip pods",
    features: [
      "Gold-tone AIROVA metal bit detail",
      "Slip-on construction with elastic gussets",
      "Cushioned, breathable insole",
      "Ivory contrast midsole",
      "Non-marking durable outsole",
    ],
    images: G("black-denim-slip-on-loafer-1"),
    badge: null,
    featured: false,
    bestSeller: false,
    newArrival: false,
    active: true,
    rating: 4.5,
    reviewCount: 1,
    createdAt: "2026-03-06T00:00:00Z",
    variants: makeVariants("black-denim-slip-on-loafer", "Black"),
  },
  {
    id: "prod-denim-3",
    name: "White Denim Slip-On Loafer",
    slug: "white-denim-slip-on-loafer",
    gender: "UNISEX",
    categorySlug: "loafers",
    category: { name: "Loafers", slug: "loafers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "White",
    colors: [{ name: "White", hex: "#f5f5f4" }],
    price: 2199,
    mrp: 3499,
    description:
      "Off-white denim with tan lining and gold detailing. The warm-weather loafer that goes with linen, chinos and everything in your summer wardrobe.",
    material: "Washed white denim upper, tan cushioned lining, memory footbed, EVA wedge with rubber grip pods",
    features: [
      "Gold-tone AIROVA metal bit detail",
      "Slip-on construction with elastic gussets",
      "Cushioned, breathable insole",
      "Tonal stitching for a clean finish",
      "Non-marking durable outsole",
    ],
    images: G("white-denim-slip-on-loafer-1"),
    badge: "New",
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 5.0,
    reviewCount: 1,
    createdAt: "2026-03-07T00:00:00Z",
    variants: makeVariants("white-denim-slip-on-loafer", "White"),
  },
  {
    id: "prod-denim-4",
    name: "Sky Blue Denim Slip-On Loafer",
    slug: "sky-blue-denim-slip-on-loafer",
    gender: "WOMEN",
    categorySlug: "loafers",
    category: { name: "Loafers", slug: "loafers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Sky Blue",
    colors: [{ name: "Sky Blue", hex: "#8ec5e8" }],
    price: 2199,
    mrp: 3499,
    description:
      "A soft sky-blue wash on our classic penny-loafer last. Light, airy and easy — the shoe for long lunches and longer walks.",
    material: "Washed sky-blue denim upper, tan cushioned lining, memory footbed, EVA wedge with rubber grip pods",
    features: [
      "Gold-tone AIROVA metal bit detail",
      "Slip-on construction with elastic gussets",
      "Cushioned, breathable insole",
      "Lightweight — ideal for all-day wear",
      "Non-marking durable outsole",
    ],
    images: G("sky-blue-denim-slip-on-loafer-1"),
    badge: "New",
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 4.8,
    reviewCount: 1,
    createdAt: "2026-03-08T00:00:00Z",
    variants: makeVariants("sky-blue-denim-slip-on-loafer", "Sky Blue"),
  },
  {
    id: "prod-denim-5",
    name: "Black Denim Low-Top Sneaker",
    slug: "black-denim-low-top-sneaker",
    gender: "UNISEX",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Black",
    colors: [{ name: "Black", hex: "#111111" }],
    price: 1999,
    mrp: 3299,
    description:
      "Washed black denim, gold eyelets and a chunky ivory cupsole. The everyday low-top that quietly dresses up jeans, tees and everything else.",
    material: "Washed black denim upper, gold-tone metal eyelets, cotton lace, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Everyday style — office to weekend",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("black-denim-low-top-sneaker-1"),
    badge: "Best Seller",
    featured: false,
    bestSeller: true,
    newArrival: false,
    active: true,
    rating: 4.6,
    reviewCount: 2,
    createdAt: "2026-03-09T00:00:00Z",
    variants: makeVariants("black-denim-low-top-sneaker", "Black"),
  },
  {
    id: "prod-denim-6",
    name: "White Denim Low-Top Sneaker",
    slug: "white-denim-low-top-sneaker",
    gender: "WOMEN",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "White",
    colors: [{ name: "White", hex: "#f5f5f4" }],
    price: 1999,
    mrp: 3299,
    description:
      "Crystal-washed white denim with warm gold hardware — the clean white sneaker, done properly.",
    material: "Washed white denim upper, gold-tone metal eyelets, cotton lace, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Crisp white wash that pairs with everything",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("white-denim-low-top-sneaker-1"),
    badge: "Best Seller",
    featured: false,
    bestSeller: true,
    newArrival: false,
    active: true,
    rating: 4.7,
    reviewCount: 2,
    createdAt: "2026-03-10T00:00:00Z",
    variants: makeVariants("white-denim-low-top-sneaker", "White"),
  },
  {
    id: "prod-denim-7",
    name: "Indigo Denim Low-Top Sneaker",
    slug: "indigo-denim-low-top-sneaker",
    gender: "MEN",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Indigo",
    colors: [{ name: "Indigo", hex: "#2c4a7c" }],
    price: 2099,
    mrp: 3499,
    description:
      "Deep indigo denim with contrast cream stitching — a classic blue that fades beautifully with wear.",
    material: "Rigid indigo denim upper, contrast cream stitching, gold-tone metal eyelets, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Classic blue denim that ages with you",
      "Contrast cream stitching",
      "Gold-tone eyelets and AIROVA lace charm",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("indigo-denim-low-top-sneaker-1"),
    badge: null,
    featured: false,
    bestSeller: false,
    newArrival: false,
    active: true,
    rating: 4.4,
    reviewCount: 1,
    createdAt: "2026-03-11T00:00:00Z",
    variants: makeVariants("indigo-denim-low-top-sneaker", "Indigo"),
  },
  {
    id: "prod-denim-8",
    name: "Classic Blue Denim Low-Top Sneaker",
    slug: "classic-blue-denim-low-top-sneaker",
    gender: "MEN",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Classic Blue",
    colors: [{ name: "Classic Blue", hex: "#3f6ea6" }],
    price: 2099,
    mrp: 3499,
    description:
      "The signature mid-blue wash from the Denim Edit — worn-in from day one, better with every mile.",
    material: "Mid-wash denim upper, gold-tone metal eyelets, cotton lace, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Signature mid-blue wash",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("classic-blue-denim-low-top-sneaker-1"),
    badge: null,
    featured: false,
    bestSeller: false,
    newArrival: false,
    active: true,
    rating: 4.5,
    reviewCount: 1,
    createdAt: "2026-03-12T00:00:00Z",
    variants: makeVariants("classic-blue-denim-low-top-sneaker", "Classic Blue"),
  },
  {
    id: "prod-denim-9",
    name: "Light Blue Denim Low-Top Sneaker",
    slug: "light-blue-denim-low-top-sneaker",
    gender: "UNISEX",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Sky Blue",
    colors: [{ name: "Sky Blue", hex: "#8ec5e8" }],
    price: 1999,
    mrp: 3299,
    description:
      "A pale, sun-faded blue that reads summer all year. Lightweight, breathable and impossibly easy to wear.",
    material: "Light-wash denim upper, gold-tone metal eyelets, cotton lace, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Sun-faded light wash",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("light-blue-denim-low-top-sneaker-1"),
    badge: "New",
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 4.3,
    reviewCount: 1,
    createdAt: "2026-03-13T00:00:00Z",
    variants: makeVariants("light-blue-denim-low-top-sneaker", "Sky Blue"),
  },
  {
    id: "prod-denim-10",
    name: "Pink Denim Low-Top Sneaker",
    slug: "pink-denim-low-top-sneaker",
    gender: "WOMEN",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Pink",
    colors: [{ name: "Pink", hex: "#e9a9bd" }],
    price: 1999,
    mrp: 3299,
    description:
      "A dusty rose denim wash with gold hardware and a cream sole. Sweet, but with an edge.",
    material: "Washed pink denim upper, gold-tone metal eyelets, cotton lace, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Dusty rose wash",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("pink-denim-low-top-sneaker-1"),
    badge: "New",
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true,
    rating: 4.6,
    reviewCount: 2,
    createdAt: "2026-03-14T00:00:00Z",
    variants: makeVariants("pink-denim-low-top-sneaker", "Pink"),
  },
  {
    id: "prod-denim-11",
    name: "Charcoal Denim Low-Top Sneaker",
    slug: "charcoal-denim-low-top-sneaker",
    gender: "MEN",
    categorySlug: "sneakers",
    category: { name: "Sneakers", slug: "sneakers" },
    collectionSlug: "denim",
    collection: { name: "Denim", slug: "denim", tagline: "The Denim Edit — Worn in, never worn out." },
    colorName: "Charcoal",
    colors: [{ name: "Charcoal", hex: "#3a3a3c" }],
    price: 2099,
    mrp: 3499,
    description:
      "Charcoal-washed denim with tonal stitching — the darkest shoe in the Denim Edit and the easiest to keep clean.",
    material: "Charcoal-washed denim upper, tonal stitching, gold-tone metal eyelets, cushioned EVA midsole, vulcanised rubber outsole",
    features: [
      "Dark charcoal wash — hides everyday wear",
      "Gold-tone eyelets and AIROVA lace charm",
      "Padded collar and tongue",
      "Cushioned EVA footbed",
      "Durable vulcanised rubber sole",
    ],
    images: G("charcoal-denim-low-top-sneaker-1"),
    badge: null,
    featured: false,
    bestSeller: false,
    newArrival: false,
    active: true,
    rating: 4.5,
    reviewCount: 1,
    createdAt: "2026-03-15T00:00:00Z",
    variants: makeVariants("charcoal-denim-low-top-sneaker", "Charcoal"),
  },
];
